version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge